export const RELATED_TO_CURRENCY = "usd" as const;

export const TICKER_COIN_MAP: { [key: string]: string } = {
  om: "OmiseGO",
  pengu: "Penguin Coin",
  ldo: "Lido DAO",
  sui: "Sui",
  boden: "Boden Coin",
  sushi: "SushiSwap",
  vet: "VeChain",
  pyusd: "PayPal USD",
  usdc: "USD Coin",
  myro: "Myro",
  snx: "Synthetix",
  zil: "Zilliqa",
  strk: "Stark",
  ars: "Argentine Peso",
  grt: "Graph Token",
  aave: "Aave",
  apt: "Aptos",
  icp: "Internet Computer",
  ada: "Cardano",
  usdt: "Tether",
  dai: "Dai",
  yfi: "yearn.finance",
  bnb: "Binance Coin",
  bonus: "Bonus Coin",
  jup: "Jupiter",
  bttc: "BitTorrent",
  eos: "EOS",
  eigen: "Eiger Coin",
  op: "Optimism",
  imx: "Immutable X",
  gala: "Gala",
  tcad: "Tether CAD",
  ethw: "Ethereum PoW",
  pepe: "Pepe",
  cati: "Cati Coin",
  xrp: "Ripple",
  w: "W Coin",
  tremp: "Tremp",
  near: "Near Protocol",
  bonk: "Bonk",
  floki: "Floki Inu",
  nzds: "NZD Stablecoin",
  qnt: "Quant",
  banana: "Banana Token",
  fet: "Fetch.ai",
  ena: "Ena",
  wif: "Wif",
  arb: "Arbitrum",
  yhdl: "YHDL",
  fil: "Filecoin",
  mxn: "Mexican Peso",
  pendle: "Pendle",
  mav: "Maverick",
  dash: "Dash",
  mana: "Decentraland",
  not: "Notional",
  trx: "TRON",
  cad: "Canadian Dollar",
  mkr: "Maker",
  aud: "Australian Dollar",
  flr: "Flare",
  eth: "Ethereum",
  silly: "Silly Coin",
  eur: "Euro",
  sgb: "Songbird",
  io: "IoTeX",
  atom: "Cosmos",
  gmt: "STEPN",
  omg: "OMG Network",
  stx: "Stacks",
  popcat: "PopCat",
  ftt: "FTX Token",
  wen: "Wen",
  btc: "Bitcoin",
  xchf: "CryptoFranc",
  link: "ChainLink",
  gbp: "British Pound",
  cake: "PancakeSwap",
  bat: "Basic Attention Token",
  yhdlbeta: "YHDL Beta",
  avax: "Avalanche",
  sol: "Solana",
  ltc: "Litecoin",
  render: "Render",
  dogs: "Dogs",
  pax: "Paxos Standard",
  ilv: "Illuvium",
  euroc: "Euro Coin",
  "1inch": "1inch",
  bnt: "Bancor",
  usual: "Usual",
  s: "S Network",
  me: "MyEtherWallet",
  pyth: "Pyth Network",
  tgbp: "TrueGBP",
  hmstr: "Hamster",
  inj: "Injective",
  ftm: "Fantom",
  tusd: "TrueUSD",
  flow: "Flow",
  xlm: "Stellar",
  gyen: "Gyen",
  mnt: "MNT",
  dot: "Polkadot",
  pol: "Polkadex",
  doge: "Dogecoin",
  jasmy: "JasmyCoin",
  theta: "Theta",
  thkd: "HKD Stablecoin",
  ray: "Raydium",
  meme: "Meme",
  sand: "The Sandbox",
  uni: "Uniswap",
  paxg: "PAX Gold",
  taud: "TrueAUD",
  luna: "Terra",
  xtz: "Tezos",
  axs: "Axie Infinity",
  chf: "Swiss Franc",
  zro: "Zero",
  wld: "Worldcoin",
  trump: "TrumpCoin",
  people: "ConstitutionDAO",
  zrx: "0x",
  bars: "Bars",
  mhix: "MHIX",
  move: "Move",
  egld: "Elrond",
  bsv: "Bitcoin SV",
  ape: "ApeCoin",
  comp: "Compound",
  xaut: "Tether Gold",
  shib: "Shiba Inu",
  ton: "Toncoin",
  usdp: "Pax Dollar",
  eurs: "STASIS EURO",
  lista: "Lista",
  bch: "Bitcoin Cash",
  ondo: "Ondo",
} as const;
